name: Actualizar canal.m3u8

on:
  schedule:
    - cron: '*/30 * * * *'  # Ejecutar cada 30 minutos, ajusta según necesites
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install yt-dlp

      - name: Ejecutar script para generar canal.m3u8
        run: python3 generar_canal.py

      - name: Commit y Push de canal.m3u8
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add canal.m3u8
          git commit -m "Actualización automática de canal.m3u8" || echo "No hay cambios"
          git push
